### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by crayzeigh** [devopsct/DevOpsDaysHartford2017#2]
I've only investigated this slightly. Since August is no longer a restriction I'm thinking early Q4 is a good time. It's busy season, but for a reason, that's fine. We'll be part of the problem. 

Velocity is Oct 1-4 so that's right out. We'll 100% lose people to velocity not to mention sponsors and speakers.

So I think that leaves us with Weeks 2-3 in Oct and 1-2 full weeks in November before we hit December and Winter sucks. Therefore:

### October
* 10-11-12
* 17-18-19
* 24-25-26
  * Potential, but getting close to halloween, not much of an issue though, mostly my anniversary which is the 28th
* then we have halloween following weeks which makes planning difficult.

### November
* 7-8-9
* 14-15-16
* Then we run into Thanksgiving time and this will get dicey for planning.
* 27-12/1 - AWS re:Invent

**Comment by crayzeigh** [comment]
To clarify, it's a 2-day event, the 3-day blocks are preferential on Tuesday-Wednesday-Thursday so the event would be 2 of those 3 days as availability permits.

**Comment by mego22** [comment]
AWS re:Invent is Nov. 27nd - Dec. 1st this year. The second or third week in October feels like a good date.

**Comment by crayzeigh** [comment]
h2. Connecticut Convention Center
Offered dates of 10/31 - 11/1 at a cost of about $40,000 for catering and event space. (8,100 for space, 32,000 for catering)

Those dates are terrible for a number of reasons so I'm looking to see if they have other dates before working on cost (There are 5 rooms including the big room and we might be able to split that room up, etc.) But the catering is going to be a big cost with no real way around that.

**Comment by crayzeigh** [comment]
Marriott initial info: 

Nov 14-15 available. 
Prices are mostly a la carte for what you want to include:
* Food
* WiFi
* Electricity at Vendor Booths
* AV

gives us flexibility in pricing, but also note: pricing not built into this final number. That said, 
we're looking at about $1500-$2000/day or about half the cost of the Convention Center before food.

**Comment by crayzeigh** [comment]
Society Room of Hartford is a possibility

**Comment by crayzeigh** [comment]
The Society Room of Hartford suddenly became my favored spot. I'm going to get food pricing details and update the venues section with the preferred options.

**Comment by crayzeigh** [comment]
Dates have been decided as October 10-11 2017
